#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Nicolas Matheus Ferreira'
        hostname: ubuntu-desktop
        username: nicolas
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
    	- brave-browser
    	- obs-studio
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

